### ISSUE TITLE
HTTPS Connection Issue 

### ISSUE THREAD

**Issue by ScottLiuGitHub** [arduino-libraries/AzureIoT#4]
Hello,

I am using Arduino Zero + Wifi 101 shield.

I have followed the instruction list at 
https://github.com/Azure/azure-iot-sdks/blob/master/doc/get_started/arduinoide-arduino-wifi101-c.md

I was able to update firmware and certificate using the instruction. However, when I ran the simplesample_http program, I got the following https connection error:

Attempting to connect to SSID: 
Connected to wifi
Info: IoT Hub SDK for C, version 1.0.0-preview.7
IoTHubClient accepted the message for delivery
Error: Time:Sat Apr 2 15:09:38 2016 File:C:\Users\liyangz\Documents\Arduino\libraries\AzureIoT\src\httpapi.cpp Func:HTTPAPI_Init Line:27 Fetching NTP epoch time failed!
Info: Fetched NTP epoch time is: 1459609915

...\Arduino\libraries\AzureIoT\src\httpapi.cpp Func:HTTPAPI_CreateConnection Line:69 HTTPS connection to failed
...\Arduino\libraries\AzureIoT\src\sdk\httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:476 unable to recover sending to a working state
...\Arduino\libraries\AzureIoT\src\sdk\iothubtransporthttp.c Func:DoEvent Line:1206 unable to HTTPAPIEX_ExecuteRequest

Anyone can help how to troubleshoot this? Thanks

**Comment by sandeepmistry** [comment]
Hi @ScottLiuGitHub,

Let's start my double checking the root SSL certificate is flashed correctly:

1. Open up the WiFi101 [WiFiSSLClient.ino](https://github.com/arduino-libraries/WiFi101/blob/master/examples/WiFiSSLClient/WiFiSSLClient.ino) example sketch
2. Fill in your SSID and password.
3. Determine the host to connect to from the Azure connection string, for example in ```HostName=SandeepTest.azure-devices.net;SharedAccessKeyName=<sakn>;SharedAccessKey=<sak>``` the host is ```SandeepTest.azure-devices.net```.
4. Change the ```char server[] = "www.google.com";``` and ```client.println("Host: www.google.com");``` lines with your Azure host from 3)
5. Save and upload the sketch.
6. If all is setup correctly, the following will be outputted:
```
...

Starting connection to server...
connected to server
HTTP/1.1 404 Not Found
Content-Length: 0
Server: Microsoft-HTTPAPI/2.0
Date: Tue, 05 Apr 2016 17:41:37 GMT
Connection: close


disconnecting from server.
```

If that looks ok, you can also enable debugging in the HTTPSClient class, by uncommenting [this](https://github.com/arduino-libraries/AzureIoT/blob/master/src/util/HTTPSClient.cpp#L6) line.

**Comment by ScottLiuGitHub** [comment]
Thanks much!

**Comment by sandeepmistry** [comment]
@ScottLiuGitHub any updates on this? Can we close it?

**Comment by ScottLiuGitHub** [comment]
Yes, please. Thanks!
